
<?php

return [
    'APP_URL' => env('APP_URL'),
    'URL' => env('URL'),
    'ADMIN_EMAIL' => env('ADMIN_EMAIL'),
    'WELCOME_TEXT' => env('WELCOME_TEXT'),
    'ADMIN_NAME' => env('ADMIN_NAME'),
    'ADMIN_NUMBER' => env('ADMIN_NUMBER'),
    'COMPANY_REG' => env('COMPANY_REG'),
    'COMPANY_NUMBER' => env('COMPANY_NUMBER'),
    'COMPANY_ADDRESS' => env('COMPANY_ADDRESS'),
    'JUMBOTRON_TEXT_COLOUR' => env('JUMBOTRON_TEXT_COLOUR'),
    'JUMBOTRON_BACKGROUND_COLOUR' => env('JUMBOTRON_BACKGROUND_COLOUR'),
    'JUMBOTRON_HEADING' => env('JUMBOTRON_HEADING'),
    'JUMBOTRON_LOGO' => env('JUMBOTRON_LOGO'),
    'NAV_BUTTON_COLOUR' => env('NAV_BUTTON_COLOUR'),
    'JUMBOTRON_TEXT' => env('JUMBOTRON_TEXT'),
    'COMPANY_NAME' => env('COMPANY_NAME'),
    'NAME' => env('NAME'),
    'PDF_LOGO' => env('PDF_LOGO'),
    'SITE_ID' => env('SITE_ID'),
    'PDF_FOOTER_ADDRESS' => env('PDF_FOOTER_ADDRESS'),
];
